// ── Quiz catalog —  9 domains × 3 levels × 5 questions × 4 options ──────────

export type Level = "easy" | "medium" | "hard";

export interface Question {
  text: string;
  options: [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
  explanation: string;
}

export interface Quiz {
  id: string;
  title: string;
  domain: string;
  description: string;
  icon: string;
  gradient: string;        // tailwind gradient classes for card accent
  questions: Record<Level, Question[]>;
}

// ── Helper: keeps TS happy with literal tuple types ───────────────────────────
function q(
  text: string,
  options: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
  explanation: string
): Question {
  return { text, options, correctIndex, explanation };
}

// ─────────────────────────────────────────────────────────────────────────────
export const quizzes: Quiz[] = [

  // ── 1. JavaScript ──────────────────────────────────────────────────────────
  {
    id: "javascript",
    title: "JavaScript",
    domain: "Programming Language",
    description: "Core JS concepts — closures, async, prototypes, and the event loop.",
    icon: "⚡",
    gradient: "from-yellow-500/20 to-amber-600/10",
    questions: {
      easy: [
        q("Which keyword declares a block-scoped variable in modern JavaScript?",
          ["var", "let", "const", "function"],
          1,
          "`let` is block-scoped. `var` is function-scoped and `const` is block-scoped but immutable."),
        q("What does `typeof null` return?",
          ["null", "undefined", "object", "boolean"],
          2,
          "This is a long-standing JS quirk — `typeof null === 'object'` although null is not an object."),
        q("Which method converts a JSON string to a JavaScript object?",
          ["JSON.stringify()", "JSON.parse()", "JSON.convert()", "JSON.toObject()"],
          1,
          "`JSON.parse()` deserialises a JSON string into a JS value."),
        q("What will `2 + '3'` evaluate to in JavaScript?",
          ["5", "23", "NaN", "Error"],
          1,
          "The `+` operator coerces the number to a string and concatenates: '23'."),
        q("Which array method returns a new filtered array?",
          ["forEach", "map", "filter", "reduce"],
          2,
          "`filter()` returns a new array with elements that pass the test function."),
      ],
      medium: [
        q("What is the output of `console.log(0.1 + 0.2 === 0.3)` in JavaScript?",
          ["true", "false", "undefined", "NaN"],
          1,
          "Floating-point arithmetic is imprecise; 0.1 + 0.2 yields 0.30000000000000004."),
        q("Which of the following correctly uses a Promise?",
          ["new Promise((res)=>res(1)).then(v=>console.log(v))",
           "Promise.new((res)=>res(1)).then(v=>console.log(v))",
           "Promise((res)=>res(1)).then(v=>console.log(v))",
           "new Promise(res=>res(1)).catch(v=>console.log(v))"],
          0,
          "Promises are created with `new Promise((resolve, reject) => ...)` and chained with `.then()`."),
        q("What does the `spread` operator (`...`) do when used with an array?",
          ["Merges two arrays into a nested array",
           "Expands elements of an iterable into individual items",
           "Creates a deep clone of an array",
           "Filters undefined values from an array"],
          1,
          "The spread operator unpacks iterable elements, e.g. `[...a, ...b]` merges arrays."),
        q("What is a closure in JavaScript?",
          ["A function that closes the browser tab",
           "A function and its reference to its surrounding lexical scope",
           "A method that hides class properties",
           "A way to terminate loops early"],
          1,
          "A closure gives a nested function access to variables in its outer scope even after the outer function returns."),
        q("Which statement about `this` in arrow functions is true?",
          ["Arrow functions bind their own `this`",
           "Arrow functions inherit `this` from their enclosing lexical context",
           "`this` is always `undefined` inside arrow functions",
           "`this` always refers to the global object"],
          1,
          "Arrow functions do not have their own `this`; they capture it from the surrounding scope."),
      ],
      hard: [
        q("What is the output of: `(function(){ return typeof arguments; })()`?",
          ["undefined", "object", "array", "function"],
          1,
          "`arguments` is an array-like object, so `typeof arguments === 'object'`."),
        q("Which micro-task runs first after the current execution context finishes?",
          ["setTimeout callback", "Promise.then callback", "setImmediate callback", "requestAnimationFrame callback"],
          1,
          "Promise callbacks are micro-tasks and drain before macro-tasks like setTimeout."),
        q("What does `Object.create(null)` produce?",
          ["null", "An empty object with no prototype chain", "An object inheriting from Object.prototype", "A frozen empty object"],
          1,
          "`Object.create(null)` creates an object with no prototype at all — no `toString`, `hasOwnProperty`, etc."),
        q("Which pattern does the module system `(IIFE)` primarily solve?",
          ["Asynchronous loading", "Avoiding global namespace pollution", "Tree-shaking unused code", "Type safety"],
          1,
          "IIFEs wrap code in a function scope, preventing variable leakage into the global namespace."),
        q("What is the time complexity of looking up a key in a JavaScript Map?",
          ["O(n)", "O(log n)", "O(1)", "O(n²)"],
          2,
          "Map uses a hash table internally, giving average O(1) lookup time."),
      ],
    },
  },

  // ── 2. Python ─────────────────────────────────────────────────────────────
  {
    id: "python",
    title: "Python",
    domain: "Programming Language",
    description: "Python fundamentals — syntax, data structures, OOP, and idiomatic patterns.",
    icon: "🐍",
    gradient: "from-blue-500/20 to-cyan-600/10",
    questions: {
      easy: [
        q("Which data type is immutable in Python?",
          ["list", "dict", "tuple", "set"],
          2,
          "Tuples cannot be changed after creation, making them immutable."),
        q("What is the output of `print(type([]))` ?",
          ["<class 'list'>", "<class 'array'>", "<type 'list'>", "list"],
          0,
          "`[]` is a list, so `type([])` returns `<class 'list'>`."),
        q("Which keyword is used to define a function in Python?",
          ["function", "def", "fun", "lambda"],
          1,
          "Python uses `def` to define a named function."),
        q("How do you create a virtual environment in Python 3?",
          ["python create venv", "python -m venv myenv", "pip install venv", "virtualenv --python3"],
          1,
          "The built-in `venv` module is invoked with `python -m venv <name>`."),
        q("What does the `len()` function return for a string?",
          ["Number of words", "Number of characters", "Number of bytes", "Number of lines"],
          1,
          "`len()` on a string returns the number of characters (not bytes)."),
      ],
      medium: [
        q("What is the output of `list(range(1,10,3))`?",
          ["[1,4,7]", "[1,3,6,9]", "[1,4,7,10]", "[1,2,3]"],
          0,
          "`range(1,10,3)` yields 1, 4, 7 (step 3, stops before 10)."),
        q("Which of these creates a generator in Python?",
          ["[x*2 for x in range(5)]", "(x*2 for x in range(5))", "{x*2 for x in range(5)}", "list(x*2 for x in range(5))"],
          1,
          "A generator expression uses parentheses `()` and is lazily evaluated."),
        q("What does the `@staticmethod` decorator do?",
          ["Makes a method private", "Allows calling a method without an instance or class reference",
           "Automatically caches method results", "Marks a method as abstract"],
          1,
          "Static methods don't receive `self` or `cls`; they behave like plain functions inside the class namespace."),
        q("What is the result of `'abc' * 3` in Python?",
          ["Error", "'abcabcabc'", "['abc','abc','abc']", "9"],
          1,
          "String repetition with `*` concatenates n copies: `'abc' * 3 == 'abcabcabc'`."),
        q("Which built-in function returns an iterator of (index, value) pairs?",
          ["zip()", "map()", "enumerate()", "iter()"],
          2,
          "`enumerate()` adds a counter to an iterable, returning (index, element) tuples."),
      ],
      hard: [
        q("What is the GIL in CPython?",
          ["Global Import Lock", "Global Interpreter Lock", "General Iteration Layer", "Generic Interface Library"],
          1,
          "The GIL is a mutex that prevents multiple native threads from executing Python bytecode simultaneously."),
        q("Which descriptor protocol method is called when an attribute is retrieved?",
          ["__set__", "__get__", "__init__", "__call__"],
          1,
          "`__get__` is invoked when the attribute is accessed on the instance."),
        q("What does `functools.lru_cache` do?",
          ["Limits recursion depth", "Memoises function results keyed by arguments", "Profiles function runtime", "Wraps a coroutine"],
          1,
          "LRU cache stores results of expensive calls and reuses them when the same inputs occur again."),
        q("What is the MRO (Method Resolution Order) algorithm used by Python 3?",
          ["Depth-First Search", "Breadth-First Search", "C3 linearisation", "Dijkstra's algorithm"],
          2,
          "Python 3 uses the C3 linearisation algorithm to determine attribute lookup order in multiple inheritance."),
        q("What will `bool(0), bool([]), bool('0')` evaluate to?",
          ["False, False, False", "False, False, True", "True, True, True", "False, True, True"],
          1,
          "`0` and `[]` are falsy; non-empty string `'0'` is truthy."),
      ],
    },
  },

  // ── 3. React ──────────────────────────────────────────────────────────────
  {
    id: "react",
    title: "React",
    domain: "Frontend Framework",
    description: "Hooks, state management, component lifecycle, and React patterns.",
    icon: "⚛️",
    gradient: "from-cyan-500/20 to-blue-600/10",
    questions: {
      easy: [
        q("Which hook is used for local component state in React?",
          ["useEffect", "useState", "useRef", "useContext"],
          1,
          "`useState` returns a stateful value and a setter function."),
        q("What is JSX?",
          ["A JavaScript test library", "A syntax extension for JS that resembles HTML", "A state management tool", "A CSS framework"],
          1,
          "JSX lets you write HTML-like markup inside JavaScript, which Babel compiles to `React.createElement` calls."),
        q("Which prop is required when rendering a list of elements?",
          ["id", "ref", "key", "name"],
          2,
          "React uses `key` to reconcile list updates efficiently; each item must have a unique key."),
        q("What does `useEffect(() => {}, [])` do?",
          ["Runs on every render", "Runs only once after the first render", "Runs before the first render", "Runs when the component unmounts only"],
          1,
          "An empty dependency array means the effect runs once after mount, like `componentDidMount`."),
        q("How do you pass data from a parent to a child component?",
          ["State", "Context", "Props", "Redux"],
          2,
          "Props are the primary mechanism for passing data down the component tree."),
      ],
      medium: [
        q("What is the purpose of `useCallback`?",
          ["Caches the result of a computation", "Memoises a function reference between renders",
           "Subscribes to a context value", "Reads a DOM element reference"],
          1,
          "`useCallback` returns a stable function reference, preventing unnecessary re-renders of child components."),
        q("Which hook should you use to read a mutable value that does NOT trigger re-renders?",
          ["useState", "useRef", "useMemo", "useReducer"],
          1,
          "`useRef` stores a mutable value in `.current` without causing re-renders when changed."),
        q("What does React's reconciliation algorithm primarily compare?",
          ["DOM node IDs", "Component names", "Virtual DOM trees", "CSS class names"],
          2,
          "React diffs the virtual DOM trees to determine the minimum set of real DOM mutations needed."),
        q("In React 18, what does `startTransition` do?",
          ["Starts a CSS transition", "Marks state updates as non-urgent, allowing urgent updates to interrupt them",
           "Defers component mounting", "Enables server-side rendering"],
          1,
          "`startTransition` lets React deprioritise wrapped state updates so urgent updates (like typing) stay responsive."),
        q("What is the correct way to update an object in state without mutating?",
          ["state.key = value; setState(state)", "setState({...state, key: value})", "setState(Object.assign(state, {key:value}))", "setState(state.key = value)"],
          1,
          "Always spread the existing state and override the changed key to produce a new object reference."),
      ],
      hard: [
        q("What pattern does the Context API + useReducer combo simulate?",
          ["Observer pattern", "Redux-like flux pattern", "Factory pattern", "Decorator pattern"],
          1,
          "Context provides the 'store' and useReducer handles state transitions, closely mirroring Redux."),
        q("When does React batch state updates in React 18?",
          ["Only inside event handlers", "Only inside useEffect", "In all async contexts including setTimeout and fetch callbacks", "Never outside of event handlers"],
          2,
          "React 18 introduces automatic batching everywhere, including async callbacks and native event listeners."),
        q("What is a render prop?",
          ["A prop whose value is a string of JSX", "A prop that is a function returning JSX, used to share logic",
           "A special internal React prop", "A prop attached to DOM elements only"],
          1,
          "Render props share stateful logic by accepting a function that returns UI, similar to HOCs."),
        q("Which React Fiber concept allows pausing and resuming render work?",
          ["Virtual DOM", "Lanes (priority queues)", "Fragments", "Portals"],
          1,
          "React Fiber uses a lane-based priority system to schedule, pause, and resume rendering work."),
        q("What does `React.memo` do?",
          ["Memoises state values", "Prevents re-render if props are shallowly equal to the previous props",
           "Caches API responses", "Marks a component as pure"],
          1,
          "`React.memo` wraps a component and skips re-rendering if incoming props haven't shallowly changed."),
      ],
    },
  },

  // ── 4. Node.js ────────────────────────────────────────────────────────────
  {
    id: "nodejs",
    title: "Node.js",
    domain: "Backend Runtime",
    description: "Event loop, streams, middleware, and server-side JavaScript patterns.",
    icon: "🟢",
    gradient: "from-green-500/20 to-emerald-600/10",
    questions: {
      easy: [
        q("What is Node.js built on top of?",
          ["SpiderMonkey", "V8 JavaScript engine", "JavaScriptCore", "Chakra"],
          1,
          "Node.js uses Google's V8 engine to execute JavaScript outside the browser."),
        q("Which module is used to create an HTTP server in Node.js?",
          ["fs", "path", "http", "net"],
          2,
          "The built-in `http` module provides `http.createServer()` to create an HTTP server."),
        q("What does `npm init -y` do?",
          ["Installs all dependencies", "Creates a package.json with default values", "Initialises a git repo", "Runs tests"],
          1,
          "`npm init -y` creates a `package.json` with all defaults, skipping prompts."),
        q("Which file lists Node project dependencies?",
          ["node_modules", "index.js", "package.json", ".npmrc"],
          2,
          "`package.json` lists dependencies, dev dependencies, scripts, and metadata."),
        q("What is the purpose of `process.env`?",
          ["Controls the event loop", "Accesses environment variables", "Lists running processes", "Manages child processes"],
          1,
          "`process.env` exposes the OS environment variables (e.g. PORT, DATABASE_URL)."),
      ],
      medium: [
        q("What is the event loop in Node.js?",
          ["A loop that automatically retries failed requests",
           "A mechanism that offloads I/O to the OS and processes callbacks when complete",
           "A while-loop that polls for new requests",
           "A built-in scheduler for timeouts only"],
          1,
          "Node's event loop delegates I/O to libuv, then calls the appropriate callbacks in phases (timers, I/O, etc.)."),
        q("Which of the following is a core Node.js built-in module?",
          ["express", "lodash", "events", "axios"],
          2,
          "`events` is built-in; the rest are third-party npm packages."),
        q("What is the difference between `require()` and `import`?",
          ["`require` is synchronous and CommonJS; `import` is ES Module and supports static analysis",
           "They are identical", "`import` is synchronous; `require` is asynchronous", "`require` only works in browsers"],
          0,
          "CommonJS `require` loads synchronously; ES Modules `import` is static and supports tree-shaking."),
        q("How does `cluster` module improve Node.js performance?",
          ["It enables async/await", "It spawns child processes to utilise multiple CPU cores",
           "It caches responses", "It provides a load balancer out of the box"],
          1,
          "`cluster` forks worker processes that share the same port, using all CPU cores."),
        q("What does `process.nextTick` do?",
          ["Pauses execution for one tick", "Schedules a callback to run before any I/O in the next iteration",
           "Sets a timeout of 0ms", "Runs a callback on the next frame"],
          1,
          "`process.nextTick` queues at the start of the next event loop iteration, before I/O callbacks."),
      ],
      hard: [
        q("Which phase of the Node.js event loop processes `setImmediate` callbacks?",
          ["Timers", "I/O callbacks", "Check", "Close callbacks"],
          2,
          "`setImmediate` runs in the check phase, after I/O callbacks and before close callbacks."),
        q("What is backpressure in Node.js streams?",
          ["The CPU pressure from heavy computations",
           "Upstream data arriving faster than downstream can consume, causing buffer buildup",
           "A technique to compress response data",
           "A rate limit enforced by the OS socket"],
          1,
          "Backpressure occurs when a writable stream cannot consume data as fast as it's pushed, stalling the readable side."),
        q("What is the purpose of the `--inspect` flag in Node.js?",
          ["Runs in strict mode", "Enables the V8 debugger protocol for Chrome DevTools",
           "Profiles memory usage", "Validates package.json"],
          1,
          "`--inspect` opens a debugging port so Chrome DevTools or VS Code can attach and debug the process."),
        q("What does `os.cpus().length` return?",
          ["The CPU clock speed", "The number of logical CPU cores", "The number of physical CPUs", "The current CPU load"],
          1,
          "`os.cpus()` returns an array with one object per logical CPU core."),
        q("Which strategy avoids blocking the event loop for CPU-intensive tasks?",
          ["Synchronous fs calls", "Worker threads or child processes", "Larger event loop iteration", "Nested callbacks"],
          1,
          "CPU-bound work should be offloaded to `worker_threads` or child processes to keep the main thread free."),
      ],
    },
  },

  // ── 5. Databases (SQL & NoSQL) ────────────────────────────────────────────
  {
    id: "databases",
    title: "Databases",
    domain: "Data Storage",
    description: "SQL fundamentals, indexing, transactions, NoSQL, and query optimisation.",
    icon: "🗄️",
    gradient: "from-purple-500/20 to-violet-600/10",
    questions: {
      easy: [
        q("Which SQL command retrieves data from a table?",
          ["INSERT", "UPDATE", "SELECT", "DELETE"],
          2,
          "`SELECT` fetches rows from one or more tables."),
        q("What does SQL stand for?",
          ["Structured Query Language", "Simple Question Language", "Sequential Query Logic", "System Query Layer"],
          0,
          "SQL — Structured Query Language — is the standard language for relational databases."),
        q("Which constraint ensures no duplicate values in a column?",
          ["NOT NULL", "PRIMARY KEY", "FOREIGN KEY", "UNIQUE"],
          3,
          "`UNIQUE` prevents duplicate values; `PRIMARY KEY` implies UNIQUE + NOT NULL."),
        q("What is a primary key?",
          ["The first column of a table", "A column (or set of columns) that uniquely identifies each row",
           "An indexed column", "A foreign reference"],
          1,
          "A primary key uniquely identifies each record and cannot be NULL."),
        q("Which type of database stores data as collections of documents?",
          ["Relational (SQL)", "Graph", "NoSQL Document", "Time-series"],
          2,
          "Document databases (e.g. MongoDB, Firestore) store data as JSON-like documents."),
      ],
      medium: [
        q("What is the purpose of an index in a database?",
          ["To enforce referential integrity", "To speed up data retrieval at the cost of extra storage and write overhead",
           "To encrypt sensitive columns", "To partition large tables"],
          1,
          "Indexes create auxiliary data structures (e.g. B-Trees) so the DB avoids full table scans."),
        q("What does ACID stand for in database transactions?",
          ["Atomicity, Consistency, Isolation, Durability",
           "Availability, Consistency, Integrity, Distribution",
           "Atomicity, Concurrency, Indexing, Durability",
           "Availability, Correctness, Isolation, Durability"],
          0,
          "ACID ensures reliable transactions: all-or-nothing (Atomic), valid state (Consistent), isolated, and persisted (Durable)."),
        q("What is a JOIN in SQL?",
          ["A syntax error", "Combining rows from two or more tables based on a related column",
           "Merging two databases", "Copying a table"],
          1,
          "JOINs combine rows from tables where the join condition is satisfied."),
        q("What distinguishes an INNER JOIN from a LEFT JOIN?",
          ["INNER JOIN returns all rows from the left table; LEFT JOIN returns only matches",
           "INNER JOIN returns only matching rows; LEFT JOIN also includes unmatched rows from the left table",
           "They are identical", "LEFT JOIN is faster"],
          1,
          "INNER JOIN excludes rows with no match; LEFT JOIN keeps all left rows and NULLs for unmatched right rows."),
        q("What is denormalisation?",
          ["Removing primary keys", "Intentionally introducing redundancy to improve read performance",
           "Converting SQL to NoSQL", "Splitting a table into smaller tables"],
          1,
          "Denormalisation trades storage for faster reads by reducing the number of JOINs needed."),
      ],
      hard: [
        q("What isolation level prevents phantom reads?",
          ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"],
          3,
          "Only SERIALIZABLE fully prevents phantom reads by locking the entire range of queried data."),
        q("What is the CAP theorem?",
          ["A theorem about CPU caches", "A distributed system can guarantee at most two of: Consistency, Availability, Partition Tolerance",
           "A theorem about SQL query cost", "A theorem about database normalisation"],
          1,
          "In a network partition, a distributed system must choose between Consistency and Availability."),
        q("What is a covering index?",
          ["An index that spans all tables", "An index containing all columns needed by a query, eliminating the need to access the main table",
           "An index with a hash function", "A composite foreign key index"],
          1,
          "A covering index lets the DB engine satisfy a query entirely from the index without touching the heap."),
        q("What does MVCC (Multi-Version Concurrency Control) achieve?",
          ["Locks rows for exclusive access", "Allows concurrent reads and writes by keeping multiple versions of each row",
           "Replicates data across nodes", "Enforces schema migrations"],
          1,
          "MVCC gives each transaction a snapshot, so readers don't block writers and vice versa."),
        q("Which normal form eliminates transitive dependencies?",
          ["1NF", "2NF", "3NF", "BCNF"],
          2,
          "Third Normal Form (3NF) requires that non-key attributes depend only on the primary key, not on other non-key attributes."),
      ],
    },
  },

  // ── 6. System Design ─────────────────────────────────────────────────────
  {
    id: "system-design",
    title: "System Design",
    domain: "Architecture",
    description: "Scalability, load balancing, caching, microservices, and design trade-offs.",
    icon: "🏗️",
    gradient: "from-orange-500/20 to-red-600/10",
    questions: {
      easy: [
        q("What is horizontal scaling?",
          ["Increasing CPU/RAM on a single server", "Adding more machines to a pool",
           "Distributing work across threads", "Caching responses"],
          1,
          "Horizontal scaling (scaling out) adds more servers; vertical scaling (scaling up) upgrades the existing server."),
        q("What is a CDN?",
          ["A code delivery network", "A content delivery network that serves assets from servers close to the user",
           "A central database node", "A continuous delivery pipeline"],
          1,
          "CDNs cache static content at edge locations globally, reducing latency."),
        q("What is the purpose of a load balancer?",
          ["Store session data", "Distribute incoming requests across multiple servers",
           "Encrypt traffic", "Monitor server health only"],
          1,
          "Load balancers distribute traffic to prevent any single server from being overwhelmed."),
        q("What is a microservice?",
          ["A tiny front-end component", "A small, independently deployable service that handles a single business domain",
           "A Lambda function", "A type of database"],
          1,
          "Microservices decompose an application into focused services that can be developed and scaled independently."),
        q("What does API stand for?",
          ["Automated Programming Interface", "Application Protocol Integration",
           "Application Programming Interface", "Advanced Processing Infrastructure"],
          2,
          "An API defines how software components communicate with each other."),
      ],
      medium: [
        q("Which cache eviction policy removes the item least recently used?",
          ["FIFO", "LFU", "LRU", "Random"],
          2,
          "LRU (Least Recently Used) evicts the item that was accessed the furthest back in time."),
        q("What is eventual consistency?",
          ["Data is always consistent at all times",
           "All nodes will converge to the same value given enough time without new updates",
           "Writes always fail until the system is fully consistent",
           "A consistency model only for SQL databases"],
          1,
          "Eventual consistency allows temporary divergence between replicas, guaranteeing convergence over time."),
        q("Which messaging pattern decouples producers from consumers?",
          ["REST API", "RPC", "Message queue / pub-sub", "WebSockets"],
          2,
          "Message queues (e.g. Kafka, RabbitMQ) buffer messages so producers and consumers operate independently."),
        q("What is a circuit breaker in microservices?",
          ["A firewall rule", "A pattern that stops calling a failing service to allow it to recover",
           "A load balancing strategy", "A rate limiter"],
          1,
          "Circuit breakers detect cascading failures and short-circuit calls to unhealthy services."),
        q("What does sharding a database mean?",
          ["Encrypting it", "Creating a read replica", "Horizontally partitioning data across multiple instances",
           "Indexing all columns"],
          2,
          "Sharding splits data by a shard key across multiple DB instances to distribute load."),
      ],
      hard: [
        q("What is the difference between a message queue and a pub-sub system?",
          ["They are identical", "A message queue delivers a message to one consumer; pub-sub broadcasts to all subscribers",
           "Pub-sub is synchronous; queues are async", "Queues support more consumers"],
          1,
          "Queues use point-to-point delivery; pub-sub (e.g. Kafka topics) fans out to all interested subscribers."),
        q("What is consistent hashing primarily used for?",
          ["Encrypting session tokens", "Distributing keys across nodes so adding/removing nodes requires minimal remapping",
           "Load balancing HTTP connections", "Generating unique IDs"],
          1,
          "Consistent hashing minimises key remapping when the node set changes, critical for distributed caches."),
        q("Which strategy prevents the thundering-herd problem on cache expiry?",
          ["Redis clustering", "Probabilistic early expiry or cache-locking (mutex on cache miss)",
           "Horizontal DB scaling", "Increasing TTL indefinitely"],
          1,
          "Cache-locking ensures only one request regenerates the cache while others wait, preventing DB overload."),
        q("What is a saga pattern in distributed systems?",
          ["A synchronous two-phase commit", "A sequence of local transactions with compensating transactions on failure",
           "A database replication strategy", "A GraphQL subscription pattern"],
          1,
          "Sagas manage distributed transactions without locking resources by using compensating actions to roll back."),
        q("What is the primary advantage of CQRS?",
          ["Simplifies code by sharing one model for reads and writes",
           "Separates read and write models to optimise each independently",
           "Eliminates the need for a database", "Enforces strict consistency"],
          1,
          "CQRS (Command Query Responsibility Segregation) lets you scale and optimise reads/writes with different models."),
      ],
    },
  },

  // ── 7. DevOps & CI/CD ────────────────────────────────────────────────────
  {
    id: "devops",
    title: "DevOps & CI/CD",
    domain: "Operations",
    description: "Docker, Kubernetes, pipelines, monitoring, and deployment strategies.",
    icon: "🚀",
    gradient: "from-indigo-500/20 to-blue-700/10",
    questions: {
      easy: [
        q("What is Docker used for?",
          ["Version control", "Containerising applications for consistent environments",
           "Load balancing HTTP traffic", "Managing DNS"],
          1,
          "Docker packages an application and its dependencies into a container that runs identically everywhere."),
        q("What does CI stand for in CI/CD?",
          ["Continuous Integration", "Container Isolation", "Code Inspection", "Cloud Infrastructure"],
          0,
          "CI — Continuous Integration — automatically builds and tests code on each commit."),
        q("What is a Dockerfile?",
          ["A YAML file for Kubernetes", "A text file with instructions to build a Docker image",
           "A Docker volume definition", "A network configuration file"],
          1,
          "A Dockerfile defines the base image, dependencies, and commands to build a runnable container image."),
        q("What is the purpose of `git pull`?",
          ["Creates a new branch", "Fetches and merges changes from the remote into the current branch",
           "Pushes local commits to remote", "Stashes local changes"],
          1,
          "`git pull` fetches remote changes and merges them into your current branch."),
        q("What does CD stand for in CI/CD?",
          ["Code Deployment", "Continuous Delivery / Continuous Deployment", "Container Delivery", "Cloud Distribution"],
          1,
          "CD automates delivering and/or deploying software to staging or production environments."),
      ],
      medium: [
        q("What is a Kubernetes Pod?",
          ["A virtual machine", "The smallest deployable unit — one or more containers sharing network and storage",
           "A Kubernetes namespace", "A load balancer configuration"],
          1,
          "Pods group containers that need to share resources and lifecycle management."),
        q("What is the difference between `CMD` and `ENTRYPOINT` in a Dockerfile?",
          ["They are identical",
           "ENTRYPOINT sets the executable; CMD provides default arguments that can be overridden",
           "CMD overrides ENTRYPOINT", "ENTRYPOINT is used only on Windows"],
          1,
          "ENTRYPOINT defines the container's main process; CMD sets default arguments that `docker run` can override."),
        q("Which deployment strategy routes a small percentage of traffic to the new version first?",
          ["Blue/green", "Recreate", "Canary", "Rolling"],
          2,
          "Canary releases expose a small user subset to the new version before full rollout."),
        q("What does `kubectl apply -f deployment.yaml` do?",
          ["Deletes the deployment", "Creates or updates Kubernetes resources defined in the YAML file",
           "Lists pods", "Scales the deployment to zero"],
          1,
          "`kubectl apply` declaratively creates or updates resources defined in the manifest."),
        q("What is an artifact in a CI/CD pipeline?",
          ["A failed test", "The output of a build step (e.g. compiled binary, Docker image) passed to subsequent stages",
           "A version control tag", "A configuration file"],
          1,
          "Artifacts are build outputs stored between pipeline stages (e.g. JAR files, images)."),
      ],
      hard: [
        q("What is the difference between a liveness probe and a readiness probe in Kubernetes?",
          ["They are identical",
           "Liveness restarts a failing container; readiness controls whether traffic is sent to the pod",
           "Readiness restarts the pod; liveness removes it from the service",
           "Both only affect initial startup"],
          1,
          "Liveness probes detect dead containers; readiness probes prevent traffic until the app is fully initialised."),
        q("What is GitOps?",
          ["Using Git as a CI runner", "Declaring the desired state of infrastructure/apps in Git and syncing automatically",
           "A Git branching strategy", "A code review workflow"],
          1,
          "GitOps treats Git as the single source of truth; operators like Argo CD apply changes automatically."),
        q("What is an Ingress in Kubernetes?",
          ["A firewall rule", "An API object that manages external HTTP/HTTPS access to services inside the cluster",
           "A storage volume", "A secret management resource"],
          1,
          "Ingress routes external traffic to ClusterIP services using host rules and path-based routing."),
        q("Which Kubernetes object ensures a specified number of pod replicas are always running?",
          ["Service", "ConfigMap", "ReplicaSet / Deployment", "StatefulSet"],
          2,
          "A ReplicaSet (managed by a Deployment) continuously reconciles the actual vs desired pod count."),
        q("What is the purpose of `--no-cache` in `docker build`?",
          ["Disables the container filesystem cache",
           "Forces Docker to rebuild each layer ignoring the layer cache",
           "Removes dangling images", "Disables network access during build"],
          1,
          "`--no-cache` ensures Docker re-executes every layer, useful for fetching the latest dependencies."),
      ],
    },
  },

  // ── 8. Data Structures & Algorithms ─────────────────────────────────────
  {
    id: "dsa",
    title: "Data Structures & Algorithms",
    domain: "Computer Science",
    description: "Complexity, arrays, trees, graphs, sorting, and classic algorithms.",
    icon: "🧠",
    gradient: "from-pink-500/20 to-rose-600/10",
    questions: {
      easy: [
        q("What is the time complexity of accessing an element by index in an array?",
          ["O(n)", "O(log n)", "O(1)", "O(n²)"],
          2,
          "Arrays store elements contiguously; index access is direct memory address arithmetic — O(1)."),
        q("Which data structure operates on a LIFO (Last In, First Out) principle?",
          ["Queue", "Stack", "Linked List", "Heap"],
          1,
          "A stack pushes and pops from the same end — the most recently added item is removed first."),
        q("What is the worst-case time complexity of bubble sort?",
          ["O(n log n)", "O(n)", "O(n²)", "O(log n)"],
          2,
          "Bubble sort compares adjacent pairs in nested loops — O(n²) in the worst case."),
        q("Which traversal visits nodes in order: Left → Root → Right?",
          ["Pre-order", "In-order", "Post-order", "Level-order"],
          1,
          "In-order traversal of a BST yields elements in ascending sorted order."),
        q("What data structure is best for implementing a BFS?",
          ["Stack", "Queue", "Heap", "Array"],
          1,
          "BFS explores level by level using a queue (FIFO) to process nodes in the order they were discovered."),
      ],
      medium: [
        q("What is the average time complexity of a hash table lookup?",
          ["O(n)", "O(log n)", "O(1)", "O(n log n)"],
          2,
          "Hash tables compute the bucket address in constant time on average, assuming a good hash function."),
        q("What does Dijkstra's algorithm find?",
          ["The minimum spanning tree", "The shortest path from a source to all vertices in a weighted graph",
           "A topological sort", "The maximum flow in a network"],
          1,
          "Dijkstra greedily picks the unvisited vertex with the smallest tentative distance, building the shortest path tree."),
        q("What is the space complexity of a recursive DFS on a graph with V vertices and E edges?",
          ["O(E)", "O(V)", "O(V + E)", "O(1)"],
          1,
          "The call stack can grow up to O(V) deep in the worst case (a linear graph)."),
        q("Which sorting algorithm has the best average-case time complexity?",
          ["Bubble Sort", "Insertion Sort", "Merge Sort", "Selection Sort"],
          2,
          "Merge Sort is O(n log n) average and worst case, unlike O(n²) algorithms."),
        q("What property must a max-heap satisfy?",
          ["Every node is less than its children", "Every node is greater than or equal to its children",
           "The tree is sorted in ascending order", "All leaves are at the same level"],
          1,
          "In a max-heap, every parent ≥ its children, so the root is always the maximum element."),
      ],
      hard: [
        q("What is the time complexity of building a heap from an unsorted array?",
          ["O(n log n)", "O(n)", "O(log n)", "O(n²)"],
          1,
          "Heapify bottom-up takes O(n) because lower levels dominate and have fewer operations."),
        q("Which algorithm finds strongly connected components in a directed graph?",
          ["Dijkstra's", "Prim's", "Kosaraju's / Tarjan's", "Bellman-Ford"],
          2,
          "Kosaraju's and Tarjan's algorithms find SCCs with two DFS passes and one DFS with a stack respectively."),
        q("What is amortised O(1) insertion mean for a dynamic array?",
          ["Every single insertion is O(1)",
           "The average cost per insertion over a long sequence is O(1), even though occasional resizing is O(n)",
           "Insertion at the front is O(1)", "Memory allocation is free"],
          1,
          "Doubling-size resizing spreads O(n) copy cost over n insertions, giving amortised O(1) per push."),
        q("What is the purpose of a sentinel node in a linked list?",
          ["To mark the middle of the list", "To simplify edge-case handling at the head and tail without null checks",
           "To store metadata about the list", "To speed up random access"],
          1,
          "Sentinel (dummy) nodes eliminate special-casing for empty list and boundary insertions/deletions."),
        q("Which data structure supports O(log n) rank queries and updates?",
          ["Segment Tree or Fenwick Tree (BIT)", "Hash Map", "Array", "Doubly Linked List"],
          0,
          "Segment Trees and Fenwick Trees support range queries and point updates in O(log n)."),
      ],
    },
  },

  // ── 9. CSS & Web Design ──────────────────────────────────────────────────
  {
    id: "css-design",
    title: "CSS & Web Design",
    domain: "UI / Styling",
    description: "Flexbox, Grid, animations, responsive design, and modern CSS patterns.",
    icon: "🎨",
    gradient: "from-fuchsia-500/20 to-pink-600/10",
    questions: {
      easy: [
        q("Which CSS property controls the space between an element's border and its content?",
          ["margin", "padding", "gap", "spacing"],
          1,
          "`padding` is the inner space between content and border; `margin` is the outer space."),
        q("What does `display: flex` do?",
          ["Hides the element", "Turns the element into a flex container, arranging children in a row or column",
           "Makes the element fixed position", "Adds an outline to the element"],
          1,
          "Flexbox enables one-dimensional layout — align and distribute space among children along a main axis."),
        q("Which unit is relative to the root element's font size?",
          ["em", "rem", "px", "vw"],
          1,
          "`rem` (root em) is relative to the `<html>` font size, making it predictable unlike `em`."),
        q("What does the CSS `box-model` consist of?",
          ["Content, border, margin, color", "Content, padding, border, margin",
           "Content, shadow, outline, margin", "Text, image, border, padding"],
          1,
          "The box model is content → padding → border → margin, from inside to outside."),
        q("Which property makes a background image cover the full element?",
          ["background-size: contain", "background-size: cover", "background-fill: full", "object-fit: cover"],
          1,
          "`background-size: cover` scales the image to cover the container while maintaining aspect ratio."),
      ],
      medium: [
        q("Which CSS Grid property defines the size of columns?",
          ["grid-template-rows", "grid-template-columns", "column-gap", "grid-auto-flow"],
          1,
          "`grid-template-columns` sets the number and size of columns, e.g. `1fr 1fr 1fr`."),
        q("What is the difference between `position: absolute` and `position: fixed`?",
          ["They are identical",
           "`absolute` positions relative to the nearest positioned ancestor; `fixed` positions relative to the viewport",
           "`fixed` positions relative to its parent; `absolute` relative to the viewport",
           "`absolute` scrolls with content; `fixed` does not scroll — both"],
          1,
          "`absolute` uses the nearest positioned ancestor; `fixed` stays in the same viewport position regardless of scroll."),
        q("What does `z-index` control?",
          ["Zoom level of an element", "The stacking order on the z-axis (which element appears on top)",
           "The opacity", "The element's rotation"],
          1,
          "Higher `z-index` values appear in front of elements with lower values (within the same stacking context)."),
        q("Which CSS pseudo-class targets an element when the user hovers over it?",
          [":focus", ":hover", ":active", ":visited"],
          1,
          "`:hover` applies styles when the pointer is over the element."),
        q("What is a CSS custom property (variable)?",
          ["A vendor prefix", "A value defined with `--name` and reused with `var(--name)` across the stylesheet",
           "A shorthand property", "A media query breakpoint"],
          1,
          "CSS variables (`--primary: #3b82f6`) are defined on a selector and consumed with `var(--primary)`."),
      ],
      hard: [
        q("What is a CSS stacking context?",
          ["A block formatting context", "An isolated layer where z-index values are compared only among siblings within it",
           "A flex container", "A named grid area"],
          1,
          "Certain properties (opacity < 1, transform, filter, etc.) create new stacking contexts that isolate z-index comparisons."),
        q("What does `will-change: transform` do?",
          ["Immediately transforms the element", "Hints the browser to promote the element to its own compositor layer",
           "Disables transitions", "Forces GPU rendering always"],
          1,
          "`will-change` hints the browser to prepare an optimised rendering path, reducing jank on upcoming changes."),
        q("What is the difference between `visibility: hidden` and `display: none`?",
          ["They are identical",
           "`visibility: hidden` hides the element but it still occupies space; `display: none` removes it from layout",
           "`display: none` hides but keeps space; `visibility: hidden` removes it from flow",
           "Only `display: none` is accessible to screen readers"],
          1,
          "`visibility: hidden` preserves the layout slot; `display: none` collapses it entirely."),
        q("Which value of `overflow` clips content and enables scrolling within the element?",
          ["visible", "hidden", "scroll", "auto"],
          3,
          "`overflow: auto` adds scrollbars only when content overflows; `scroll` always shows scrollbars."),
        q("What does `@supports` do in CSS?",
          ["Imports external stylesheets", "Conditionally applies styles based on whether the browser supports a CSS feature",
           "Defines animation keyframes", "Sets browser-specific prefixes"],
          1,
          "`@supports` (feature queries) lets you write progressive enhancement — apply styles only when the browser supports them."),
      ],
    },
  },
];

export const getQuiz = (id: string): Quiz | undefined =>
  quizzes.find((q) => q.id === id);
